import { useState, useEffect } from "react";
import jsPDF from "jspdf";
import { applyPlugin } from "jspdf-autotable";
applyPlugin(jsPDF);
import "./Admin.css";

// ─── PDF Generators (for admin download from stored service_logs) ───

const sanitize = (text) => {
  if (text == null) return "N/A";
  return String(text)
    .replace(/₹/g, "Rs.")
    .replace(/°/g, " deg")
    .replace(/–/g, "-")
    .replace(/—/g, "-")
    .replace(/\u2018/g, "'")
    .replace(/\u2019/g, "'")
    .replace(/\u201c/g, '"')
    .replace(/\u201d/g, '"')
    .replace(/…/g, "...")
    .replace(/[^\x00-\x7F]/g, "");
};

function generateCropPDF(crops, form) {
  const date = new Date().toLocaleDateString("en-IN", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const green = [0, 166, 118];
  const s = sanitize;

  doc.setFillColor(...green);
  doc.rect(0, 0, pageWidth, 32, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("KrishiMitra AI - Crop Advisor Report", pageWidth / 2, 15, {
    align: "center",
  });
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("AI-Powered Smart Farming Platform", pageWidth / 2, 24, {
    align: "center",
  });

  doc.setFillColor(240, 247, 244);
  doc.roundedRect(14, 38, pageWidth - 28, 22, 3, 3, "F");
  doc.setTextColor(60, 60, 60);
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...green);
  doc.text("Location: ", 18, 46);
  doc.text("Farm Size: ", 18, 53);
  doc.text("Crop Type: ", 95, 46);
  doc.text("Last Crop: ", 95, 53);
  doc.text("Date: ", 165, 46);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(30, 30, 30);
  doc.text(s(form?.location || "N/A"), 40, 46);
  doc.text(
    s(`${form?.farm_size || "N/A"} ${form?.farm_size_unit || ""}`),
    42,
    53,
  );
  doc.text(s(form?.crop_type || "N/A"), 120, 46);
  doc.text(s(form?.last_crop || "N/A"), 120, 53);
  doc.text(date, 178, 46);

  const tableBody = [];
  (crops || []).forEach((crop, i) => {
    tableBody.push([
      i + 1,
      s(crop.name),
      s(crop.expectedYield),
      s(crop.waterRequirement),
      s(crop.profitMargin),
      `${crop.suitability || 85}%`,
    ]);
    tableBody.push([
      {
        content: `Reason: ${s(crop.season)}`,
        colSpan: 6,
        styles: {
          fillColor: [248, 250, 248],
          textColor: [100, 100, 100],
          fontSize: 8,
          fontStyle: "italic",
        },
      },
    ]);
  });

  doc.autoTable({
    startY: 66,
    head: [
      [
        "#",
        "Crop Name",
        "Expected Yield",
        "Water Needs",
        "Market Price",
        "Match",
      ],
    ],
    body: tableBody,
    theme: "grid",
    headStyles: {
      fillColor: green,
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 9,
    },
    bodyStyles: { fontSize: 9, textColor: [30, 30, 30] },
    columnStyles: {
      0: { cellWidth: 10, halign: "center" },
      5: { halign: "center" },
    },
    margin: { left: 14, right: 14 },
    styles: { cellPadding: 4, lineColor: [226, 232, 240], lineWidth: 0.3 },
  });

  const finalY = doc.lastAutoTable.finalY + 14;
  doc.setDrawColor(226, 232, 240);
  doc.line(14, finalY, pageWidth - 14, finalY);
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(
    `Generated by KrishiMitra AI on ${date}`,
    pageWidth / 2,
    finalY + 7,
    { align: "center" },
  );
  doc.save(`Crop_Advisor_${Date.now()}.pdf`);
}

function generateDiseasePDF(result) {
  const date = new Date().toLocaleDateString("en-IN", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const green = [0, 166, 118];
  const s = sanitize;

  const sevColors = {
    none: [40, 167, 69],
    low: [40, 167, 69],
    medium: [255, 193, 7],
    high: [220, 53, 69],
  };
  const sevKey = (result.severity || "none").toLowerCase();
  const sevColor = sevColors[sevKey] || [136, 136, 136];

  doc.setFillColor(...green);
  doc.rect(0, 0, pageWidth, 32, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("KrishiMitra AI - Disease Detection Report", pageWidth / 2, 15, {
    align: "center",
  });
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("AI-Powered Smart Farming Platform", pageWidth / 2, 24, {
    align: "center",
  });

  doc.setFillColor(248, 250, 248);
  doc.setDrawColor(...sevColor);
  doc.setLineWidth(0.8);
  doc.roundedRect(14, 38, pageWidth - 28, 20, 3, 3, "FD");
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(26, 29, 35);
  doc.text(s(result.diseaseName || "Unknown"), 20, 48);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text(`Confidence: ${s(result.confidence || "N/A")}`, 20, 54);
  doc.setFillColor(...sevColor);
  const badgeText = (result.severity || "N/A").toUpperCase();
  const badgeW = doc.getTextWidth(badgeText) + 10;
  doc.roundedRect(pageWidth - 18 - badgeW, 43, badgeW, 10, 2, 2, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.text(badgeText, pageWidth - 18 - badgeW / 2, 49.5, { align: "center" });

  let y = 66;
  const drawSectionTitle = (title) => {
    if (y > 265) {
      doc.addPage();
      y = 20;
    }
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...green);
    doc.text(title, 14, y);
    y += 2;
    doc.setDrawColor(226, 232, 240);
    doc.setLineWidth(0.3);
    doc.line(14, y, pageWidth - 14, y);
    y += 5;
  };
  const drawList = (items) => {
    if (!items || !items.length) return;
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(50, 50, 50);
    items.forEach((item) => {
      if (y > 275) {
        doc.addPage();
        y = 20;
      }
      const lines = doc.splitTextToSize(`- ${s(item)}`, pageWidth - 34);
      doc.text(lines, 18, y);
      y += lines.length * 4.5;
    });
    y += 3;
  };
  const drawInfoTable = (rows) => {
    doc.autoTable({
      startY: y,
      body: rows,
      theme: "plain",
      styles: {
        fontSize: 9,
        cellPadding: 3,
        lineColor: [226, 232, 240],
        lineWidth: 0.2,
      },
      columnStyles: {
        0: { fontStyle: "bold", textColor: green, cellWidth: 45 },
        1: { textColor: [50, 50, 50] },
      },
      margin: { left: 14, right: 14 },
    });
    y = doc.lastAutoTable.finalY + 8;
  };

  if (result.symptoms?.length || result.causes?.length) {
    drawSectionTitle("Symptoms");
    drawList(result.symptoms);
    drawSectionTitle("Causes");
    drawList(result.causes);
  }
  if (result.treatment?.length || result.prevention?.length) {
    drawSectionTitle("Treatment");
    drawList(result.treatment);
    drawSectionTitle("Prevention");
    drawList(result.prevention);
  }
  if (result.additionalTips?.length) {
    drawSectionTitle("Additional Tips");
    drawList(result.additionalTips);
  }
  if (result.irrigationPlan) {
    drawSectionTitle("Irrigation Plan");
    drawInfoTable([
      ["Frequency", s(result.irrigationPlan.frequency)],
      ["Quantity", s(result.irrigationPlan.quantity)],
      ["Best Time", s(result.irrigationPlan.bestTime)],
      ["Method", s(result.irrigationPlan.method)],
    ]);
  }
  if (result.pesticide) {
    drawSectionTitle("Pesticide Details");
    drawInfoTable([
      ["Type", s(result.pesticide.type)],
      ["Amount", s(result.pesticide.amount)],
      ["Application", s(result.pesticide.applicationMethod)],
      ["Frequency", s(result.pesticide.frequency)],
      ["Safety Period", s(result.pesticide.safetyPeriod)],
    ]);
  }
  if (result.soilSuggestions) {
    drawSectionTitle("Soil Suggestions");
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(50, 50, 50);
    const soilLines = doc.splitTextToSize(
      s(result.soilSuggestions),
      pageWidth - 34,
    );
    if (y + soilLines.length * 4.5 > 275) {
      doc.addPage();
      y = 20;
    }
    doc.text(soilLines, 18, y);
    y += soilLines.length * 4.5 + 5;
  }
  if (result.sprinklerSchedule?.length) {
    drawSectionTitle("Sprinkler Schedule");
    doc.autoTable({
      startY: y,
      head: [["Day", "Time", "Action"]],
      body: result.sprinklerSchedule.map((item) => [
        s(item.day),
        s(item.time),
        s(item.action),
      ]),
      theme: "grid",
      headStyles: {
        fillColor: green,
        textColor: [255, 255, 255],
        fontStyle: "bold",
        fontSize: 9,
      },
      bodyStyles: { fontSize: 9, textColor: [50, 50, 50] },
      margin: { left: 14, right: 14 },
      styles: { cellPadding: 4, lineColor: [226, 232, 240], lineWidth: 0.3 },
    });
    y = doc.lastAutoTable.finalY + 8;
  }
  if (y > 270) {
    doc.addPage();
    y = 20;
  }
  doc.setDrawColor(226, 232, 240);
  doc.line(14, y, pageWidth - 14, y);
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(`Generated by KrishiMitra AI on ${date}`, pageWidth / 2, y + 7, {
    align: "center",
  });
  doc.save(
    `Disease_Report_${(result.diseaseName || "Unknown").replace(/\s+/g, "_")}_${Date.now()}.pdf`,
  );
}

export default function Admin() {
  const [token, setToken] = useState(
    sessionStorage.getItem("admin_token") || "",
  );
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [loginError, setLoginError] = useState("");
  const [loggingIn, setLoggingIn] = useState(false);

  const [view, setView] = useState("dashboard"); // dashboard | user-detail
  const [stats, setStats] = useState(null);
  const [users, setUsers] = useState([]);
  const [selectedUser, setSelectedUser] = useState(null);
  const [userDetail, setUserDetail] = useState(null);
  const [loadingData, setLoadingData] = useState(false);
  const [search, setSearch] = useState("");
  const [filterType, setFilterType] = useState("all"); // all | google | guest

  const isLoggedIn = !!token;

  const apiCall = async (action, extra = {}) => {
    const res = await fetch("/api/admin", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${token}`,
      },
      body: JSON.stringify({ action, ...extra }),
    });
    if (res.status === 401) {
      setToken("");
      sessionStorage.removeItem("admin_token");
      return null;
    }
    return res.json();
  };

  const handleLogin = async (e) => {
    e.preventDefault();
    setLoggingIn(true);
    setLoginError("");
    try {
      const res = await fetch("/api/admin", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ action: "login", username, password }),
      });
      const data = await res.json();
      if (res.ok && data.token) {
        setToken(data.token);
        sessionStorage.setItem("admin_token", data.token);
      } else {
        setLoginError(data.error || "Invalid credentials");
      }
    } catch {
      setLoginError("Connection failed");
    } finally {
      setLoggingIn(false);
    }
  };

  const handleLogout = () => {
    setToken("");
    sessionStorage.removeItem("admin_token");
  };

  // Load dashboard data
  useEffect(() => {
    if (!isLoggedIn) return;
    const load = async () => {
      setLoadingData(true);
      const [statsData, usersData] = await Promise.all([
        apiCall("stats"),
        apiCall("users"),
      ]);
      if (statsData) setStats(statsData);
      if (usersData) setUsers(usersData.users || []);
      setLoadingData(false);
    };
    load();
  }, [isLoggedIn]);

  const viewUserDetail = async (user) => {
    setSelectedUser(user);
    setView("user-detail");
    setLoadingData(true);
    const data = await apiCall("user-detail", { userId: user.id });
    if (data) setUserDetail(data);
    setLoadingData(false);
  };

  const filteredUsers = users.filter((u) => {
    const matchesSearch =
      !search ||
      (u.name || "").toLowerCase().includes(search.toLowerCase()) ||
      (u.email || "").toLowerCase().includes(search.toLowerCase()) ||
      (u.ip_address || "").includes(search);
    const matchesFilter =
      filterType === "all" ||
      (filterType === "google" && !u.is_guest) ||
      (filterType === "guest" && u.is_guest);
    return matchesSearch && matchesFilter;
  });

  const formatDate = (iso) => {
    if (!iso) return "N/A";
    return new Date(iso).toLocaleDateString("en-IN", {
      day: "numeric",
      month: "short",
      year: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    });
  };

  const serviceLabel = (s) => {
    const map = {
      crop_recommendation: "Crop Advisor",
      disease_detection: "Disease Detection",
      sprinkler_analysis: "Sprinkler Analysis",
      weather: "Weather",
      marketplace: "Marketplace",
      chatbot: "Chatbot",
    };
    return map[s] || s;
  };

  const serviceIcon = (s) => {
    const map = {
      crop_recommendation: "fa-seedling",
      disease_detection: "fa-virus",
      sprinkler_analysis: "fa-tint",
      weather: "fa-cloud-sun",
      marketplace: "fa-store",
      chatbot: "fa-robot",
    };
    return map[s] || "fa-cog";
  };

  // ─── LOGIN VIEW ───
  if (!isLoggedIn) {
    return (
      <div className="admin-login-page">
        <div className="admin-login-card">
          <div className="admin-login-header">
            <i className="fas fa-leaf"></i>
            <h1>KrishiMitra Admin</h1>
            <p>Dashboard Access</p>
          </div>
          <form onSubmit={handleLogin}>
            <div className="admin-form-group">
              <i className="fas fa-user"></i>
              <input
                type="text"
                placeholder="Username"
                value={username}
                onChange={(e) => setUsername(e.target.value)}
                required
              />
            </div>
            <div className="admin-form-group">
              <i className="fas fa-lock"></i>
              <input
                type="password"
                placeholder="Password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                required
              />
            </div>
            {loginError && <div className="admin-error">{loginError}</div>}
            <button
              type="submit"
              disabled={loggingIn}
              className="admin-login-btn"
            >
              {loggingIn ? (
                <>
                  <i className="fas fa-spinner fa-spin"></i> Signing in...
                </>
              ) : (
                <>
                  <i className="fas fa-sign-in-alt"></i> Sign In
                </>
              )}
            </button>
          </form>
        </div>
      </div>
    );
  }

  // ─── USER DETAIL VIEW ───
  if (view === "user-detail" && selectedUser) {
    return (
      <div className="admin-page">
        <div className="admin-topbar">
          <button
            className="admin-back-btn"
            onClick={() => {
              setView("dashboard");
              setUserDetail(null);
            }}
          >
            <i className="fas fa-arrow-left"></i> Back
          </button>
          <h2>User Details</h2>
          <button className="admin-logout-btn" onClick={handleLogout}>
            <i className="fas fa-sign-out-alt"></i>
          </button>
        </div>

        {loadingData ? (
          <div className="admin-loading">
            <i className="fas fa-spinner fa-spin"></i> Loading...
          </div>
        ) : userDetail ? (
          <div className="admin-detail-grid">
            {/* Profile Card */}
            <div className="admin-card admin-profile-card">
              <div className="admin-profile-header">
                {selectedUser.picture ? (
                  <img
                    src={selectedUser.picture}
                    alt=""
                    className="admin-avatar"
                  />
                ) : (
                  <div className="admin-avatar-placeholder">
                    <i
                      className={`fas ${selectedUser.is_guest ? "fa-user-secret" : "fa-user"}`}
                    ></i>
                  </div>
                )}
                <div>
                  <h3>{selectedUser.name || "Guest"}</h3>
                  <p className="admin-email">
                    {selectedUser.email || selectedUser.ip_address || "N/A"}
                  </p>
                  <span
                    className={`admin-badge ${selectedUser.is_guest ? "guest" : "google"}`}
                  >
                    {selectedUser.is_guest ? "Guest" : "Google"}
                  </span>
                </div>
              </div>
              <div className="admin-profile-details">
                <div className="admin-detail-row">
                  <span>Location</span>
                  <strong>{selectedUser.location || "Not set"}</strong>
                </div>
                <div className="admin-detail-row">
                  <span>IoT Device</span>
                  <strong>
                    {selectedUser.has_device ? "Connected" : "Not connected"}
                  </strong>
                </div>
                <div className="admin-detail-row">
                  <span>Joined</span>
                  <strong>{formatDate(selectedUser.created_at)}</strong>
                </div>
                <div className="admin-detail-row">
                  <span>Last Login</span>
                  <strong>{formatDate(selectedUser.last_login)}</strong>
                </div>
                {selectedUser.ip_address && (
                  <div className="admin-detail-row">
                    <span>IP Address</span>
                    <strong>{selectedUser.ip_address}</strong>
                  </div>
                )}
              </div>
            </div>

            {/* Blockchain Records */}
            <div className="admin-card">
              <h3>
                <i className="fas fa-link"></i> Blockchain Records ({(userDetail.blockchainRecords || []).length})
              </h3>
              {(userDetail.blockchainRecords || []).length === 0 ? (
                <p className="admin-empty-text">No blockchain records found</p>
              ) : (
                <div className="admin-plans-list">
                  {(userDetail.blockchainRecords || []).map((record) => (
                    <div key={record.id} className="admin-plan-item" style={{ borderLeft: "3px solid #00a676" }}>
                      <div className="admin-plan-header">
                        <strong>
                          <i className="fas fa-file-contract"></i> {String(record.record_type).replace("_", " ").toUpperCase()}
                        </strong>
                      </div>
                      <div className="admin-plan-meta" style={{ marginTop: "8px" }}>
                        <span><i className="fas fa-hashtag"></i> {record.data_hash?.slice(0, 12)}...</span>
                        {record.ipfs_cid && <span><i className="fas fa-box"></i> CID: {record.ipfs_cid?.slice(0, 12)}...</span>}
                        <span>{formatDate(record.created_at)}</span>
                      </div>
                      {record.contract_event && (
                        <details className="admin-log-details">
                          <summary>Smart Contract Event</summary>
                          <pre>{JSON.stringify(record.contract_event, null, 2)}</pre>
                        </details>
                      )}
                    </div>
                  ))}
                </div>
              )}
            </div>

            {/* Service Usage */}
            <div className="admin-card">
              <h3>
                <i className="fas fa-chart-bar"></i> Service Usage (
                {userDetail.serviceLogs.length})
              </h3>
              {userDetail.serviceLogs.length === 0 ? (
                <p className="admin-empty-text">No service usage recorded</p>
              ) : (
                <div className="admin-log-list">
                  {userDetail.serviceLogs.map((log) => (
                    <div key={log.id} className="admin-log-item">
                      <div className="admin-log-icon">
                        <i className={`fas ${serviceIcon(log.service)}`}></i>
                      </div>
                      <div className="admin-log-content">
                        <div className="admin-log-title">
                          {serviceLabel(log.service)}
                        </div>
                        <div className="admin-log-time">
                          {formatDate(log.created_at)}
                        </div>
                        {log.form_data &&
                          (() => {
                            if (log.service === "crop_recommendation") {
                              const f = log.form_data;
                              return (
                                <div className="admin-log-summary">
                                  <span>
                                    <i className="fas fa-map-marker-alt"></i>{" "}
                                    {f.location || "N/A"}
                                  </span>
                                  <span>
                                    <i className="fas fa-ruler"></i>{" "}
                                    {f.farm_size} {f.farm_size_unit}
                                  </span>
                                  <span>
                                    <i className="fas fa-leaf"></i>{" "}
                                    {f.crop_type}
                                  </span>
                                  {f.last_crop && (
                                    <span>
                                      <i className="fas fa-history"></i>{" "}
                                      {f.last_crop}
                                    </span>
                                  )}
                                </div>
                              );
                            }
                            return (
                              <details className="admin-log-details">
                                <summary>Input Data</summary>
                                <pre>
                                  {JSON.stringify(log.form_data, null, 2)}
                                </pre>
                              </details>
                            );
                          })()}
                        {log.result_data &&
                          (() => {
                            if (log.service === "crop_recommendation") {
                              const crops = Array.isArray(log.result_data)
                                ? log.result_data
                                : log.result_data.crops || [];
                              return (
                                <div className="admin-log-pdf-row">
                                  <span className="admin-log-brief">
                                    {crops.length} crop
                                    {crops.length !== 1 ? "s" : ""} recommended
                                    {crops.length > 0 &&
                                      `: ${crops.map((c) => c.name).join(", ")}`}
                                  </span>
                                  <button
                                    className="admin-pdf-btn"
                                    onClick={(e) => {
                                      e.stopPropagation();
                                      generateCropPDF(crops, log.form_data);
                                    }}
                                  >
                                    <i className="fas fa-file-pdf"></i> Download
                                    PDF
                                  </button>
                                </div>
                              );
                            }
                            if (log.service === "disease_detection") {
                              const r = log.result_data;
                              return (
                                <div className="admin-log-pdf-row">
                                  <span className="admin-log-brief">
                                    <strong>
                                      {r.diseaseName || "Unknown"}
                                    </strong>
                                    {r.severity && (
                                      <span
                                        className={`admin-severity-inline ${(r.severity || "").toLowerCase()}`}
                                      >
                                        {r.severity}
                                      </span>
                                    )}
                                    {r.confidence && (
                                      <span> — {r.confidence}</span>
                                    )}
                                  </span>
                                  <button
                                    className="admin-pdf-btn"
                                    onClick={(e) => {
                                      e.stopPropagation();
                                      generateDiseasePDF(r);
                                    }}
                                  >
                                    <i className="fas fa-file-pdf"></i> Download
                                    PDF
                                  </button>
                                </div>
                              );
                            }
                            return (
                              <details className="admin-log-details">
                                <summary>Result Data</summary>
                                <pre>
                                  {JSON.stringify(log.result_data, null, 2)}
                                </pre>
                              </details>
                            );
                          })()}
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>

            {/* Chat History */}
            <div className="admin-card">
              <h3>
                <i className="fas fa-comments"></i> Chat History (
                {userDetail.chatHistory.length} messages)
              </h3>
              {userDetail.chatHistory.length === 0 ? (
                <p className="admin-empty-text">No chat messages</p>
              ) : (
                <div className="admin-chat-list">
                  {userDetail.chatHistory.map((msg) => (
                    <div key={msg.id} className={`admin-chat-msg ${msg.role}`}>
                      <div className="admin-chat-role">
                        {msg.role === "user" ? "User" : "AI"}
                      </div>
                      <div className="admin-chat-text">{msg.text}</div>
                      <div className="admin-chat-time">
                        {formatDate(msg.created_at)}
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>

            {/* Sprinkler Plans */}
            <div className="admin-card">
              <h3>
                <i className="fas fa-tachometer-alt"></i> Sprinkler Plans (
                {userDetail.sprinklerPlans.length})
              </h3>
              {userDetail.sprinklerPlans.length === 0 ? (
                <p className="admin-empty-text">No sprinkler plans</p>
              ) : (
                <div className="admin-plans-list">
                  {userDetail.sprinklerPlans.map((plan) => (
                    <div key={plan.id} className="admin-plan-item">
                      <div className="admin-plan-header">
                        <strong>{plan.disease_name}</strong>
                        <span
                          className={`admin-severity ${(plan.severity || "none").toLowerCase()}`}
                        >
                          {plan.severity}
                        </span>
                      </div>
                      <div className="admin-plan-meta">
                        <span>Confidence: {plan.confidence}</span>
                        <span>Sprays: {plan.spray_count}</span>
                        <span>Status: {plan.status}</span>
                        <span>{formatDate(plan.created_at)}</span>
                      </div>
                      {plan.irrigation_plan && (
                        <details className="admin-log-details">
                          <summary>Irrigation Plan</summary>
                          <pre>
                            {JSON.stringify(plan.irrigation_plan, null, 2)}
                          </pre>
                        </details>
                      )}
                    </div>
                  ))}
                </div>
              )}
            </div>

            {/* User Fields */}
            <div className="admin-card">
              <h3>
                <i className="fas fa-map-marked-alt"></i> Mapped Fields (
                {(userDetail.userFields || []).length})
              </h3>
              {(userDetail.userFields || []).length === 0 ? (
                <p className="admin-empty-text">No fields mapped</p>
              ) : (
                <div className="admin-plans-list">
                  {(userDetail.userFields || []).map((field) => (
                    <div key={field.id} className="admin-plan-item">
                      <div className="admin-plan-header">
                        <strong>
                          <i className="fas fa-map"></i>{" "}
                          {field.name || "Unnamed Field"}
                        </strong>
                      </div>
                      <div className="admin-plan-meta">
                        <span>
                          <i className="fas fa-ruler-combined"></i>{" "}
                          {field.area_sqm
                            ? field.area_sqm >= 10000
                              ? `${(field.area_sqm / 10000).toFixed(2)} ha`
                              : field.area_sqm >= 4046.86
                                ? `${(field.area_sqm / 4046.86).toFixed(2)} acres`
                                : `${field.area_sqm.toFixed(0)} m²`
                            : "—"}
                        </span>
                        <span>
                          <i className="fas fa-map-pin"></i>{" "}
                          {field.coordinates?.length || 0} points
                        </span>
                        <span>{formatDate(field.created_at)}</span>
                      </div>
                      {field.coordinates && (
                        <details className="admin-log-details">
                          <summary>Coordinates</summary>
                          <pre>
                            {JSON.stringify(field.coordinates, null, 2)}
                          </pre>
                        </details>
                      )}
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>
        ) : null}
      </div>
    );
  }

  // ─── DASHBOARD VIEW ───
  return (
    <div className="admin-page">
      <div className="admin-topbar">
        <div className="admin-topbar-left">
          <i className="fas fa-leaf"></i>
          <h2>KrishiMitra Admin</h2>
        </div>
        <button className="admin-logout-btn" onClick={handleLogout}>
          <i className="fas fa-sign-out-alt"></i> Logout
        </button>
      </div>

      {loadingData && !stats ? (
        <div className="admin-loading">
          <i className="fas fa-spinner fa-spin"></i> Loading dashboard...
        </div>
      ) : (
        <>
          {/* Stats Cards */}
          {stats && (
            <div className="admin-stats-grid">
              <div className="admin-stat-card">
                <div className="admin-stat-icon google">
                  <i className="fas fa-users"></i>
                </div>
                <div className="admin-stat-info">
                  <div className="admin-stat-number">{stats.totalUsers}</div>
                  <div className="admin-stat-label">Google Users</div>
                </div>
              </div>
              <div className="admin-stat-card">
                <div className="admin-stat-icon guest">
                  <i className="fas fa-user-secret"></i>
                </div>
                <div className="admin-stat-info">
                  <div className="admin-stat-number">{stats.guestUsers}</div>
                  <div className="admin-stat-label">Guest Users</div>
                </div>
              </div>
              <div className="admin-stat-card">
                <div className="admin-stat-icon services">
                  <i className="fas fa-chart-line"></i>
                </div>
                <div className="admin-stat-info">
                  <div className="admin-stat-number">{stats.totalLogs}</div>
                  <div className="admin-stat-label">Service Uses</div>
                </div>
              </div>
              <div className="admin-stat-card">
                <div className="admin-stat-icon plans">
                  <i className="fas fa-tachometer-alt"></i>
                </div>
                <div className="admin-stat-info">
                  <div className="admin-stat-number">{stats.activePlans}</div>
                  <div className="admin-stat-label">Active Plans</div>
                </div>
              </div>
              <div className="admin-stat-card">
                <div className="admin-stat-icon chats">
                  <i className="fas fa-comments"></i>
                </div>
                <div className="admin-stat-info">
                  <div className="admin-stat-number">{stats.chatMessages}</div>
                  <div className="admin-stat-label">Chat Messages</div>
                </div>
              </div>
              <div className="admin-stat-card">
                <div
                  className="admin-stat-icon"
                  style={{
                    background: "rgba(76,175,80,0.12)",
                    color: "#4caf50",
                  }}
                >
                  <i className="fas fa-map-marked-alt"></i>
                </div>
                <div className="admin-stat-info">
                  <div className="admin-stat-number">
                    {stats.totalFields || 0}
                  </div>
                  <div className="admin-stat-label">Mapped Fields</div>
                </div>
              </div>
            </div>
          )}

          {/* Users Section */}
          <div className="admin-users-section">
            <div className="admin-users-header">
              <h3>All Users ({filteredUsers.length})</h3>
              <div className="admin-filters">
                <div className="admin-search">
                  <i className="fas fa-search"></i>
                  <input
                    type="text"
                    placeholder="Search by name, email, or IP..."
                    value={search}
                    onChange={(e) => setSearch(e.target.value)}
                  />
                </div>
                <div className="admin-filter-btns">
                  {["all", "google", "guest"].map((f) => (
                    <button
                      key={f}
                      className={`admin-filter-btn ${filterType === f ? "active" : ""}`}
                      onClick={() => setFilterType(f)}
                    >
                      {f === "all"
                        ? "All"
                        : f === "google"
                          ? "Google"
                          : "Guest"}
                    </button>
                  ))}
                </div>
              </div>
            </div>

            <div className="admin-users-table">
              <div className="admin-table-header">
                <span>User</span>
                <span>Location</span>
                <span>Joined</span>
                <span>Services</span>
                <span></span>
              </div>
              {filteredUsers.map((u) => (
                <div
                  key={u.id}
                  className="admin-table-row"
                  onClick={() => viewUserDetail(u)}
                >
                  <div className="admin-user-cell">
                    {u.picture ? (
                      <img
                        src={u.picture}
                        alt=""
                        className="admin-user-avatar"
                      />
                    ) : (
                      <div className="admin-user-avatar-placeholder">
                        <i
                          className={`fas ${u.is_guest ? "fa-user-secret" : "fa-user"}`}
                        ></i>
                      </div>
                    )}
                    <div>
                      <div className="admin-user-name">{u.name || "Guest"}</div>
                      <div className="admin-user-email">
                        {u.email || u.ip_address || "N/A"}
                      </div>
                    </div>
                    <span
                      className={`admin-badge-sm ${u.is_guest ? "guest" : "google"}`}
                    >
                      {u.is_guest ? "Guest" : "Google"}
                    </span>
                  </div>
                  <span className="admin-cell-location">
                    {u.location || "—"}
                  </span>
                  <span className="admin-cell-date">
                    {formatDate(u.created_at)}
                  </span>
                  <span className="admin-cell-count">
                    {u.service_count || 0}
                  </span>
                  <span className="admin-cell-action">
                    <i className="fas fa-chevron-right"></i>
                  </span>
                </div>
              ))}
              {filteredUsers.length === 0 && (
                <div className="admin-empty-row">No users found</div>
              )}
            </div>
          </div>
        </>
      )}
    </div>
  );
}
