import { useState } from "react";
import { motion } from "framer-motion";
import { useAuth } from "../context/AuthContext";
import {
  logService,
  hasGuestUsedService,
  markGuestServiceUsed,
} from "../lib/supabase";
import { useBlockchain } from "../context/BlockchainContext";
import jsPDF from "jspdf";
import { applyPlugin } from "jspdf-autotable";
applyPlugin(jsPDF);
import "./CropRecommendation.css";

function generateCropPDF(crops, form) {
  const date = new Date().toLocaleDateString("en-IN", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const green = [0, 166, 118];

  const s = (text) => {
    if (text == null) return "N/A";
    return String(text)
      .replace(/₹/g, "Rs.")
      .replace(/°/g, " deg")
      .replace(/–/g, "-")
      .replace(/—/g, "-")
      .replace(/\u2018/g, "'")
      .replace(/\u2019/g, "'")
      .replace(/\u201c/g, '"')
      .replace(/\u201d/g, '"')
      .replace(/…/g, "...")
      .replace(/[^\x00-\x7F]/g, "");
  };

  doc.setFillColor(...green);
  doc.rect(0, 0, pageWidth, 32, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("KrishiMitra AI - Crop Advisor Report", pageWidth / 2, 15, {
    align: "center",
  });
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("AI-Powered Smart Farming Platform", pageWidth / 2, 24, {
    align: "center",
  });

  doc.setFillColor(240, 247, 244);
  doc.roundedRect(14, 38, pageWidth - 28, 22, 3, 3, "F");
  doc.setTextColor(60, 60, 60);
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...green);
  doc.text("Location: ", 18, 46);
  doc.text("Farm Size: ", 18, 53);
  doc.text("Crop Type: ", 95, 46);
  doc.text("Last Crop: ", 95, 53);
  doc.text("Date: ", 165, 46);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(30, 30, 30);
  doc.text(s(form.location), 40, 46);
  doc.text(s(`${form.farm_size} ${form.farm_size_unit}`), 42, 53);
  doc.text(s(form.crop_type), 120, 46);
  doc.text(s(form.last_crop || "N/A"), 120, 53);
  doc.text(date, 178, 46);

  const tableBody = [];
  crops.forEach((crop, i) => {
    tableBody.push([
      i + 1,
      s(crop.name),
      s(crop.expectedYield),
      s(crop.waterRequirement),
      s(crop.profitMargin),
      `${crop.suitability || 85}%`,
    ]);
    tableBody.push([
      {
        content: `Reason: ${s(crop.season)}`,
        colSpan: 6,
        styles: {
          fillColor: [248, 250, 248],
          textColor: [100, 100, 100],
          fontSize: 8,
          fontStyle: "italic",
        },
      },
    ]);
  });

  doc.autoTable({
    startY: 66,
    head: [
      [
        "#",
        "Crop Name",
        "Expected Yield",
        "Water Needs",
        "Market Price",
        "Match",
      ],
    ],
    body: tableBody,
    theme: "grid",
    headStyles: {
      fillColor: green,
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 9,
    },
    bodyStyles: { fontSize: 9, textColor: [30, 30, 30] },
    columnStyles: {
      0: { cellWidth: 10, halign: "center" },
      5: { halign: "center" },
    },
    margin: { left: 14, right: 14 },
    styles: { cellPadding: 4, lineColor: [226, 232, 240], lineWidth: 0.3 },
  });

  const finalY = doc.lastAutoTable.finalY + 14;
  doc.setDrawColor(226, 232, 240);
  doc.line(14, finalY, pageWidth - 14, finalY);
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(
    `Generated by KrishiMitra AI on ${date}`,
    pageWidth / 2,
    finalY + 7,
    { align: "center" },
  );
  doc.text(
    "This report is AI-generated. Please consult local agricultural experts before making decisions.",
    pageWidth / 2,
    finalY + 13,
    { align: "center" },
  );

  doc.save(`Crop_Advisor_${form.location}_${Date.now()}.pdf`);
}

export default function CropRecommendation() {
  const { user } = useAuth();
  const blockchain = useBlockchain();
  const [form, setForm] = useState({
    location: "",
    farm_size: "",
    farm_size_unit: "acre",
    last_crop: "",
    crop_type: "Vegetables",
  });
  const [loading, setLoading] = useState(false);
  const [crops, setCrops] = useState([]);
  const [error, setError] = useState("");
  const [guestBlocked, setGuestBlocked] = useState(false);

  const handleChange = (e) =>
    setForm({ ...form, [e.target.name]: e.target.value });

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!form.location || !form.farm_size || !form.crop_type) {
      setError("Please fill all required fields");
      return;
    }

    // Guest limit check (localStorage)
    if (user?.isGuest && hasGuestUsedService("crop_recommendation")) {
      setGuestBlocked(true);
      setError(
        "Guest users can only use each service once. Please sign in with Google to continue.",
      );
      return;
    }

    setLoading(true);
    setError("");
    setCrops([]);
    try {
      const res = await fetch("/api/crop-recommend", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(form),
      });
      if (!res.ok) {
        const d = await res.json();
        throw new Error(d.error || "Analysis failed");
      }
      const data = await res.json();
      setCrops(data.crops || []);

      // Log to Supabase
      const userId = user?.dbId || null;
      if (userId) {
        logService(userId, "crop_recommendation", form, data.crops);
        // Blockchain: record on-chain + award tokens
        if (blockchain) {
          blockchain.addRecord("crop_recommendation", { form, crops: data.crops });
          blockchain.awardTokens(5, "crop_recommendation");
        }
      } else if (user?.isGuest) {
        markGuestServiceUsed("crop_recommendation");
      }
    } catch (e) {
      setError(e.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="page-container">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="page-header"
      >
        <div className="page-title">
          <i className="fas fa-seedling"></i>
          <h1>Crop Advisor</h1>
        </div>
        <p className="page-desc">
          Get AI-powered crop suggestions based on your location, soil, and
          weather conditions
        </p>
      </motion.div>

      <motion.form
        className="crop-form card"
        onSubmit={handleSubmit}
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.1 }}
      >
        <div className="form-grid">
          <div className="form-group">
            <label>
              <i className="fas fa-map-marker-alt"></i> Location *
            </label>
            <input
              name="location"
              value={form.location}
              onChange={handleChange}
              placeholder="Enter city name"
              required
            />
          </div>
          <div className="form-group">
            <label>
              <i className="fas fa-ruler"></i> Farm Size *
            </label>
            <div className="input-row">
              <input
                name="farm_size"
                type="number"
                value={form.farm_size}
                onChange={handleChange}
                placeholder="Size"
                required
                min="0"
                step="any"
              />
              <select
                name="farm_size_unit"
                value={form.farm_size_unit}
                onChange={handleChange}
              >
                <option value="acre">Acre</option>
                <option value="bigha">Bigha</option>
                <option value="yard">Sq. Yard</option>
              </select>
            </div>
          </div>
          <div className="form-group">
            <label>
              <i className="fas fa-history"></i> Last Crop Grown
            </label>
            <input
              name="last_crop"
              value={form.last_crop}
              onChange={handleChange}
              placeholder="e.g. Wheat"
            />
          </div>
          <div className="form-group">
            <label>
              <i className="fas fa-leaf"></i> Crop Type *
            </label>
            <select
              name="crop_type"
              value={form.crop_type}
              onChange={handleChange}
            >
              <option>Vegetables</option>
              <option>Fruits</option>
              <option>Grains</option>
              <option>Pulses</option>
              <option>Spices</option>
              <option>Flowers</option>
              <option>Oilseeds</option>
            </select>
          </div>
        </div>
        <button
          type="submit"
          className="analyze-btn"
          disabled={loading || guestBlocked}
        >
          {loading ? (
            <>
              <i className="fas fa-spinner fa-spin"></i> Analyzing...
            </>
          ) : (
            <>
              <i className="fas fa-search"></i> Get Recommendations
            </>
          )}
        </button>
        {error && (
          <div className="error-msg">
            <i className="fas fa-exclamation-triangle"></i> {error}
          </div>
        )}
      </motion.form>

      {crops.length > 0 && (
        <motion.div
          className="crop-results"
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
        >
          <div className="crop-grid">
            {crops.map((crop, i) => (
              <motion.div
                key={i}
                className="crop-card card"
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: i * 0.1 }}
              >
                <div className="crop-card-header">
                  <div className="crop-name">
                    <i className="fas fa-seedling"></i>
                    <span>{crop.name}</span>
                  </div>
                  <span className="crop-badge">
                    {crop.suitability || 85}% Match
                  </span>
                </div>
                <div className="crop-card-body">
                  <div className="crop-detail">
                    <i className="fas fa-chart-line"></i>
                    <span className="label">Yield:</span>
                    <span className="value">{crop.expectedYield}</span>
                  </div>
                  <div className="crop-detail">
                    <i className="fas fa-rupee-sign"></i>
                    <span className="label">Price:</span>
                    <span className="value">{crop.profitMargin}</span>
                  </div>
                  <div className="crop-detail">
                    <i className="fas fa-info-circle"></i>
                    <span className="label">Reason:</span>
                    <span className="value">{crop.season}</span>
                  </div>
                  <div className="crop-detail">
                    <i className="fas fa-tint"></i>
                    <span className="label">Water:</span>
                    <span className="value">{crop.waterRequirement}</span>
                  </div>
                </div>
              </motion.div>
            ))}
          </div>
          <button
            className="pdf-btn"
            onClick={() => generateCropPDF(crops, form)}
          >
            <i className="fas fa-file-pdf"></i> Download PDF Report
          </button>
        </motion.div>
      )}
    </div>
  );
}
